### ISSUE TITLE
ERROR! 'ascii' codec can't encode character '\u2019' in position 44: ordinal not in range(128)

### ISSUE THREAD

**Issue by themacmarketer** [tfeldmann/organize#11]
Hello,

Thanks for this nifty script!

I'm getting the error above when running it on my MacBookPro with Python 3.6.2, and was wondering if anyone might be able to help me troubleshoot.

I've attached the last few lines of the log below.

Thank you!

Cheers,
Ivan

+++

2018-08-29 03:22:36,950 - organize.actions.shell - INFO - Executing command "open "/Volumes/Transcend/Downloads/2. JACINTA_Personal Brand_30min n 15min QnA.pptx"" in shell.
2018-08-29 03:22:36,966 - organize.main - ERROR - 'ascii' codec can't encode character '\u2019' in position 44: ordinal not in range(128)
Traceback (most recent call last):
  File "/Users/ivanwong/anaconda3/lib/python3.6/site-packages/organize/main.py", line 103, in main
    execute_rules(config.rules, simulate=args['sim'])
  File "/Users/ivanwong/anaconda3/lib/python3.6/site-packages/organize/core.py", line 92, in execute_rules
    puts('File %s:' % bold(relative_path))
  File "/Users/ivanwong/anaconda3/lib/python3.6/site-packages/clint/textui/core.py", line 68, in puts
    stream(_str)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2019' in position 44: ordinal not in range(128)
2018-08-29 03:23:29,009 - organize.main - ERROR - 'ascii' codec can't encode character '\u2019' in position 44: ordinal not in range(128)
Traceback (most recent call last):
  File "/Users/ivanwong/anaconda3/lib/python3.6/site-packages/organize/main.py", line 103, in main
    execute_rules(config.rules, simulate=args['sim'])
  File "/Users/ivanwong/anaconda3/lib/python3.6/site-packages/organize/core.py", line 92, in execute_rules
    puts('File %s:' % bold(relative_path))
  File "/Users/ivanwong/anaconda3/lib/python3.6/site-packages/clint/textui/core.py", line 68, in puts
    stream(_str)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2019' in position 44: ordinal not in range(128)
2018-08-29 03:24:56,215 - organize.main - ERROR - 'ascii' codec can't encode character '\u2019' in position 44: ordinal not in range(128)
Traceback (most recent call last):
  File "/Users/ivanwong/anaconda3/lib/python3.6/site-packages/organize/main.py", line 103, in main
    execute_rules(config.rules, simulate=args['sim'])
  File "/Users/ivanwong/anaconda3/lib/python3.6/site-packages/organize/core.py", line 92, in execute_rules
    puts('File %s:' % bold(relative_path))
  File "/Users/ivanwong/anaconda3/lib/python3.6/site-packages/clint/textui/core.py", line 68, in puts
    stream(_str)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2019' in position 44: ordinal not in range(128)
2018-08-29 03:26:21,312 - organize.main - ERROR - 'ascii' codec can't encode character '\u2019' in position 44: ordinal not in range(128)
Traceback (most recent call last):
  File "/Users/ivanwong/anaconda3/lib/python3.6/site-packages/organize/main.py", line 103, in main
    execute_rules(config.rules, simulate=args['sim'])
  File "/Users/ivanwong/anaconda3/lib/python3.6/site-packages/organize/core.py", line 92, in execute_rules
    puts('File %s:' % bold(relative_path))
  File "/Users/ivanwong/anaconda3/lib/python3.6/site-packages/clint/textui/core.py", line 68, in puts
    stream(_str)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2019' in position 44: ordinal not in range(128)
2018-08-29 03:26:47,525 - organize.main - ERROR - 'ascii' codec can't encode character '\u2019' in position 44: ordinal not in range(128)
Traceback (most recent call last):
  File "/Users/ivanwong/anaconda3/lib/python3.6/site-packages/organize/main.py", line 103, in main
    execute_rules(config.rules, simulate=args['sim'])
  File "/Users/ivanwong/anaconda3/lib/python3.6/site-packages/organize/core.py", line 92, in execute_rules
    puts('File %s:' % bold(relative_path))
  File "/Users/ivanwong/anaconda3/lib/python3.6/site-packages/clint/textui/core.py", line 68, in puts
    stream(_str)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2019' in position 44: ordinal not in range(128)
2018-08-29 03:26:53,406 - organize.main - ERROR - 'ascii' codec can't encode character '\u2019' in position 44: ordinal not in range(128)
Traceback (most recent call last):
  File "/Users/ivanwong/anaconda3/lib/python3.6/site-packages/organize/main.py", line 103, in main
    execute_rules(config.rules, simulate=args['sim'])
  File "/Users/ivanwong/anaconda3/lib/python3.6/site-packages/organize/core.py", line 92, in execute_rules
    puts('File %s:' % bold(relative_path))
  File "/Users/ivanwong/anaconda3/lib/python3.6/site-packages/clint/textui/core.py", line 68, in puts
    stream(_str)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2019' in position 44: ordinal not in range(128)

**Comment by tfeldmann** [comment]
Hi, it seems you are using unicode quotation marks in your config file (`\u2019` = `’`) which is not valid yaml. Some text editors replace them automatically because they look nicer.
After replacing your quotation marks with either `"` or `'` it should work 👍
