### ISSUE TITLE
"macostags" causes error on M1 Mac

### ISSUE THREAD

**Issue by Marty56** [tfeldmann/organize#128]
The "macostags" causes the following error on M1 Mac

`
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/organize/cli.py", line 77, in main
    execute_rules(config.rules, simulate=args["sim"])
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/organize/config.py", line 161, in rules
    rule_actions = list(self.instantiate_actions(rule_item))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/organize/config.py", line 139, in instantiate_actions
    action_class = self._get_action_class_by_name(name)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/organize/config.py", line 87, in _get_action_class_by_name
    return self.action_by_name[self.sanitize_key(name)]
KeyError: 'macostags'
2021-04-27 20:18:11,822 - organize - ERROR - 'macostags'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/organize/cli.py", line 77, in main
    execute_rules(config.rules, simulate=args["sim"])
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/organize/config.py", line 161, in rules
    rule_actions = list(self.instantiate_actions(rule_item))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/organize/config.py", line 139, in instantiate_actions
    action_class = self._get_action_class_by_name(name)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/organize/config.py", line 87, in _get_action_class_by_name
    return self.action_by_name[self.sanitize_key(name)]
KeyError: 'macostags'
`

**Comment by tfeldmann** [comment]
Can you post the output of 
```
organize --version
```

 and 
```
organize list
```
?

**Comment by Marty56** [comment]
organize --version
1.9.1
 organize list
Filters:
  Created
  Duplicate
  Exif
  Extension
  FileContent
  FileSize
  Filename
  LastModified
  Python
  Regex

Actions:
  Copy
  Delete
  Echo
  Move
  Python
  Rename
  Shell

**Comment by tfeldmann** [comment]
This version is too old, macOS tags arrived in v1.10

**Comment by Marty56** [comment]
Interesting I have installed this version 2 hours ago.

**Comment by tfeldmann** [comment]
How did you install it?

**Comment by Marty56** [comment]
pip3 install -U organize-tool

**Comment by Marty56** [comment]
I may be connected to the version of python that I have installed on the M1 macBook.
I used the package python-3.9.4-macos11 which has native M1 Code.

**Comment by Marty56** [comment]
I deinstalled the python-3.9.4-macos11 and installed the version python-3.9.4-macos 10.9 and the error was gone.

**Comment by tfeldmann** [comment]
That's even more confusing! Can you check whether the newest version works with the latest python? Unfortunately I don't have a M1 machine to test.
