### ISSUE TITLE
Version 2.x filecontent not working anymore

### ISSUE THREAD

**Issue by Marty56** [tfeldmann/organize#188]
The filecontent regex is not compatible. Error is happening with pdf files.
All rules previously working containing the "filecontent" command result in error.
Tested with Version 2.09 and 2.1.

```
- (filecontent) ERROR! 'NoneType' object has no attribute 'groupdict'
```
Examples not working anymore: 

```
    filters:
      - regex: '(?P<year>20\d{2})-[01]\d-[0-3]\d.*\.pdf'  
      - filecontent:
        - '(HUK-COBURG)|(ADAC)|(Meine HUK24)|(Sozialversicherung)'
      - filecontent:
        - '(?P<strasse>Brückl)'
```
```
   filters:
      - regex: '(?P<year>20\d{2})-[01]\d-[0-3]\d.*\.pdf'
      - filecontent:
        - '(Versorgung)|(Abwasser)|(Schmutzwasser)|(Abfall)'
      - filecontent:
        - 'Brückl'
  ```

Even examples taken straight from documentation do not work anymore
```
    filters:
      - filecontent:
        - '(?P<inhalt>.*)'
```

**Comment by Marty56** [comment]
It is also occurring on matching files. See last example which is always matching.

**Comment by Marty56** [comment]
Why did you close the bug?

**Comment by tfeldmann** [comment]
Ah it got auto-closed because I named the commit `fix #188' 😅

**Comment by tfeldmann** [comment]
Please try with the dev version:

```
pip3 install git+https://github.com/tfeldmann/organize.git
```

**Comment by Marty56** [comment]
Not working. Same errors.

**Comment by tfeldmann** [comment]
Are you sure you are on the dev version? Please install again from git and run organize --version to confirm. It should be `version 2.1.0.dev`

**Comment by Marty56** [comment]
I seems that I am not running the dev version. What I have done it cut and paste 
pip3 install git+https://github.com/tfeldmann/organize.git

Am I missing a step?

**Comment by tfeldmann** [comment]
This depends on how you installed organize in the first place. You can try `which organize` (if you are not on windows) to see the installation location. Or are you using pipx maybe?

**Comment by tfeldmann** [comment]
Just a guess. Try `/Library/Frameworks/Python.framework/Versions/3.9/bin/python -m pip install -U git+https://github.com/tfeldmann/organize.git`.

**Comment by Marty56** [comment]
/Library/Frameworks/Python.framework/Versions/3.9/bin/python -m pip install -U git+https://github.com/tfeldmann/organize.git.
zsh: no such file or directory: /Library/Frameworks/Python.framework/Versions/3.9/bin/python

**Comment by Marty56** [comment]
sorry I am not a python expert.

**Comment by Marty56** [comment]
OK. Thank you.

**Comment by tfeldmann** [comment]
It's released 👍 Please update and try again!

**Comment by Marty56** [comment]
```
 organize sim                                                                                                                  
organize 2.1.1
Config: "/Users/martinklimke/Library/Mobile Documents/com~apple~CloudDocs/Documents/Organize/Rules/config.yaml"

╭───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ SIMULATION                                                                                                                                                                                                                    │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

⚙ Rule 1 ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
/Users/martinklimke/Library/Mobile Documents/com~apple~CloudDocs/Documents/Organize/category folders/steuerrelevante Rechnungen
--- Logging error ---
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/textract/parsers/utils.py", line 87, in run
    pipe = subprocess.Popen(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pdftotext'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/textract/parsers/pdf_parser.py", line 21, in extract
    return self.extract_pdftotext(filename, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/textract/parsers/pdf_parser.py", line 44, in extract_pdftotext
    stdout, _ = self.run(args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/textract/parsers/utils.py", line 95, in run
    raise exceptions.ShellError(
textract.exceptions.ShellError: The command `pdftotext /Users/martinklimke/Library/Mobile Documents/com~apple~CloudDocs/Documents/Organize/category folders/steuerrelevante Rechnungen/2021-01-01_SWM Rechnung.pdf -` failed 
because the executable
`pdftotext` is not installed on your system. Please make
sure the appropriate dependencies are installed before using
textract:

    http://textract.readthedocs.org/en/latest/installation.html


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/textract/parsers/pdf_parser.py", line 54, in extract_pdfminer
    stdout, _ = self.run(['pdf2txt.py', filename])
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/textract/parsers/utils.py", line 87, in run
    pipe = subprocess.Popen(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: 'pdf2txt.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/textract/parsers/pdf_parser.py", line 57, in extract_pdfminer
    stdout, _ = self.run(['python3',pdf2txt_path, filename])
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/textract/parsers/utils.py", line 106, in run
    raise exceptions.ShellError(
textract.exceptions.ShellError: The command `python3 /Library/Frameworks/Python.framework/Versions/3.9/bin/pdf2txt.py /Users/martinklimke/Library/Mobile Documents/com~apple~CloudDocs/Documents/Organize/category 
folders/steuerrelevante Rechnungen/2021-01-01_SWM Rechnung.pdf` failed with exit code 1
------------- stdout -------------
b''------------- stderr -------------
b'Traceback (most recent call last):\n  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/pdf2txt.py", line 7, in <module>\n    import pdfminer.high_level\nModuleNotFoundError: No module named \'pdfminer\'\n'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/organize/filters/filecontent.py", line 38, in matches
    content = textract.process(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/textract/parsers/__init__.py", line 79, in process
    return parser.process(filename, input_encoding, output_encoding, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/textract/parsers/utils.py", line 46, in process
    byte_string = self.extract(filename, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/textract/parsers/pdf_parser.py", line 27, in extract
    return self.extract_pdfminer(filename, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/textract/parsers/pdf_parser.py", line 59, in extract_pdfminer
    stdout, _ = self.run(['python2',pdf2txt_path, filename])
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/textract/parsers/utils.py", line 106, in run
    raise exceptions.ShellError(
textract.exceptions.ShellError: The command `python2 /Library/Frameworks/Python.framework/Versions/3.9/bin/pdf2txt.py /Users/martinklimke/Library/Mobile Documents/com~apple~CloudDocs/Documents/Organize/category 
folders/steuerrelevante Rechnungen/2021-01-01_SWM Rechnung.pdf` failed with exit code 1
------------- stdout -------------
b''------------- stderr -------------
b'Traceback (most recent call last):\n  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/pdf2txt.py", line 7, in <module>\n    import pdfminer.high_level\nImportError: No module named pdfminer.high_level\n'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 1083, in emit
    msg = self.format(record)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 663, in format
    record.message = record.getMessage()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 367, in getMessage
    msg = msg % self.args
ValueError: incomplete format
Call stack:
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/organize", line 8, in <module>
    sys.exit(cli())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/organize/cli.py", line 146, in sim
    run_local(config_path=config, working_dir=working_dir, simulate=True)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/organize/cli.py", line 90, in run_local
    core.run(rules=config, simulate=simulate)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/organize/core.py", line 325, in run
    count = run_rules(rules=rules, simulate=simulate)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/organize/core.py", line 272, in run_rules
    match = filter_pipeline(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/organize/core.py", line 202, in filter_pipeline
    match, updates = filter_.pipeline(args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/organize/filters/filecontent.py", line 63, in pipeline
    match = self.matches(path=syspath)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/organize/filters/filecontent.py", line 50, in matches
    logger.warning("CommandLineError %", e)
Message: 'CommandLineError %'
Arguments: (ShellError('python2 /Library/Frameworks/Python.framework/Versions/3.9/bin/pdf2txt.py /Users/martinklimke/Library/Mobile Documents/com~apple~CloudDocs/Documents/Organize/category folders/steuerrelevante 
Rechnungen/2021-01-01_SWM Rechnung.pdf', 1, b'', b'Traceback (most recent call last):\n  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/pdf2txt.py", line 7, in <module>\n    import 
pdfminer.high_level\nImportError: No module named pdfminer.high_level\n'),)

```

These error message come repeatingly.

**Comment by tfeldmann** [comment]
2.1.2 is out. please try again.

**Comment by tfeldmann** [comment]
You are still on 2.1.1

**Comment by Marty56** [comment]
Error messages are gone. But I do not get matches even with always match rules like

```
    filters:
      - filecontent:
        - '(?P<inhalt>.*)'
    actions:
      - echo: "Debug\n\n {filecontent.inhalt}"
      - echo: "----------------------------------------------------------------------------------\n\n"
  ```

**Comment by Marty56** [comment]
uninstallation and reinstallation did not resolve the issue.
I have to google how to install python3 via brew which will take a while (not today).
But version 1.x worked without those workarounds, so I honestly doubt that this will resolve the issue.

**Comment by Marty56** [comment]
This resolved the issue.
Big Thanks!!

**Comment by tfeldmann** [comment]
Oh wow! Glad to hear that!
