### ISSUE TITLE
Logging permissions error on Windows

### ISSUE THREAD

**Issue by xdhmoore** [tfeldmann/organize#207]
**Describe the bug**
On some actions (trash & shell, for example), I see the following error each time they execute. The actions still seem to work, they just print out a lot of noise:

```
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process:
'C:\\Users\\xdhmoore\\AppData\\Local\\organize\\organize\\Logs\\organize.log' ->
'C:\\Users\\xdhmoore\\AppData\\Local\\organize\\organize\\Logs\\organize.log.2022-04-10'
```

Full stack trace:

```
Traceback (most recent call last):
File "D:\tools\Python\Python38\lib\logging\handlers.py", line 70, in emit
self.doRollover()
File "D:\tools\Python\Python38\lib\logging\handlers.py", line 394, in doRollover
self.rotate(self.baseFilename, dfn)
File "D:\tools\Python\Python38\lib\logging\handlers.py", line 111, in rotate
os.rename(source, dest)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process:
'C:\\Users\\xdhmoore\\AppData\\Local\\organize\\organize\\Logs\\organize.log' ->
'C:\\Users\\xdhmoore\\AppData\\Local\\organize\\organize\\Logs\\organize.log.2022-04-10'
Call stack:
File "D:\tools\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
return _run_code(code, main_globals, None,
File "D:\tools\Python\Python38\lib\runpy.py", line 87, in _run_code
exec(code, run_globals)
File "D:\projects\.venv\Scripts\organize.exe\__main__.py", line 7, in <module>
sys.exit(cli())
File "d:\projects\.venv\lib\site-packages\click\core.py", line 1130, in __call__
return self.main(*args, **kwargs)
File "d:\projects\.venv\lib\site-packages\click\core.py", line 1055, in main
rv = self.invoke(ctx)
File "d:\projects\.venv\lib\site-packages\click\core.py", line 1657, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "d:\projects\.venv\lib\site-packages\click\core.py", line 1404, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "d:\projects\.venv\lib\site-packages\click\core.py", line 760, in invoke
return __callback(*args, **kwargs)
File "d:\projects\.venv\lib\site-packages\organize\cli.py", line 157, in run
run_local(
File "d:\projects\.venv\lib\site-packages\organize\cli.py", line 108, in run_local
core.run(
File "d:\projects\.venv\lib\site-packages\organize\core.py", line 362, in run
count = run_rules(rules=rules, tags=tags, skip_tags=skip_tags, simulate=simulate)
File "d:\projects\.venv\lib\site-packages\organize\core.py", line 322, in run_rules
is_success = action_pipeline(
File "d:\projects\.venv\lib\site-packages\organize\core.py", line 231, in action_pipeline
updates = action.pipeline(args, simulate=simulate)
File "d:\projects\.venv\lib\site-packages\organize\actions\trash.py", line 29, in pipeline
self.trash(path=fs.getsyspath(fs_path), simulate=simulate)
File "d:\projects\.venv\lib\site-packages\organize\actions\trash.py", line 23, in trash
logger.info("Moving file %s into trash.", path):
Arguments: ('F:\\myfolder\\somefile.txt',)
```

**Environment (please complete the following information):**
 - OS: Windows 10
 - Output of `organize --version`: organize, version 2.2.0

**Comment by tfeldmann** [comment]
Is it possible you have more than one process of organize running?

**Comment by xdhmoore** [comment]
Sorry for the issue. I'm not seeing this anymore. Maybe I had a zombie process or lock or something. Thanks for the response.
