### ISSUE TITLE
organize reveal results in "module termios not found"

### ISSUE THREAD

**Issue by charstnut** [tfeldmann/organize#209]
**Describe the bug**
Running `organize.exe reveal/edit` on Windows 11 (powershell) gives the error ModuleNotFoundError: No module named 'termios'.
I have also tested on the official installation of python but calling `import tty` still gives the same ModuleNotFoundError.

**Expected behavior**
organize shows the configuration file.

**Screenshots**
The following is the output of the powershell line:
```
(venv) PS D:\> organize.exe reveal
Traceback (most recent call last):
  File "E:\inkscape\lib\python3.9\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\inkscape\lib\python3.9\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\venv\bin\organize.exe\__main__.py", line 7, in <module>
  File "D:\venv\lib\python3.9\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "D:\venv\lib\python3.9\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "D:\venv\lib\python3.9\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\venv\lib\python3.9\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\venv\lib\python3.9\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "D:\venv\lib\python3.9\site-packages\organize\cli.py", line 242, in reveal
    click.launch(str(CONFIG_PATH), locate=True)
  File "D:\venv\lib\python3.9\site-packages\click\termui.py", line 710, in launch
    from ._termui_impl import open_url
  File "D:\venv\lib\python3.9\site-packages\click\_termui_impl.py", line 679, in <module>
    import tty
  File "E:\inkscape\lib\python3.9\tty.py", line 5, in <module>
    from termios import *
ModuleNotFoundError: No module named 'termios'
```

**Environment (please complete the following information):**
 - OS: Windows 11
 - Output of `organize --version`: 2.0.3

**Your config file**
```yaml
--- paste your config file here ---
```

**Comment by tfeldmann** [comment]
Are you running this out of Inkscape?

```
  File "E:\inkscape\lib\python3.9\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\inkscape\lib\python3.9\runpy.py", line 87, in _run_code
    exec(code, run_globals)
```

What is happening here? It seems to switch between a venv and this Inkscape installation?
Does the rest of `organize` work normally?

**Comment by charstnut** [comment]
The python installation is using default one coming along with Inkscape, but I installed `organize` with venv. The issue persists with official python installation not just the one under Inkscape posted here. I think it's because `termios` is not compatible with Windows. 
I have not yet tested the rest of the program and am only reporting this behavior here for the records.

**Comment by tfeldmann** [comment]
Please try again with v2.4.0
