### ISSUE TITLE
Config file doesn't work if it's a symlink (before it used to)

### ISSUE THREAD

**Issue by AdelleBernal** [tfeldmann/organize#291]
**Describe the bug**
I can't seem to use a symbolic link for the config file as I used to. 
This is very useful when you use different computers and what to have your config file in Dropbox folder, for instance.
When using a symlink as the config file and running `organize sim` or `organize run` I get the following:

```bash
Traceback (most recent call last):
  File "/opt/homebrew/bin/organize", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/organize/cli.py", line 213, in sim
    execute(
  File "/opt/homebrew/lib/python3.11/site-packages/organize/cli.py", line 147, in execute
    config_path, config_text = read_config(config)
                               ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/organize/cli.py", line 95, in read_config
    return (fs_url, confdir.readtext(filename))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/fs/base.py", line 697, in readtext
    contents = read_file.read()
               ^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb1 in position 43: invalid start byte

```
**Environment (please complete the following information):**

- OS:
- Output of `organize --version`: version 2.4.0

**Your config file**

```yaml
rules:

  - name: "DOWNLOADS"
    locations: ~/Downloads
    enabled: true
    filters:
      - extension:
        - jpg
        - jpeg
        - png 
    actions:
      - move:
          dest: "~/Downloads/IMAGE/"
          on_conflict: rename_new
          rename_template: "{name}_{counter}{extension}"

```

**Comment by kamuridesu** [comment]
I couldn't reproduce the error. Can you upload your config?
What OS are you using?

**Comment by AdelleBernal** [comment]
My config file is 

rules:

```
  - name: "DOWNLOADS"
    locations: ~/Downloads
    enabled: true
    filters:
      - extension:
        - jpg
        - jpeg
        - png 
    actions:
      - move:
          dest: "~/Downloads/IMAGE/"
          on_conflict: rename_new
          rename_template: "{name}_{counter}{extension}"
```

**Comment by kamuridesu** [comment]
Can you try to recreate your config file?
