### ISSUE TITLE
Cannot run config file saved in Google Drive (macOS Ventura)

### ISSUE THREAD

**Issue by gregoriopellegrino** [tfeldmann/organize#296]
**Describe the bug**
I run the `organize` command using the configuration file saved on Google Drive:

```
organize sim /Users/xxx/Library/CloudStorage/GoogleDrive-xxx@my.domain/My\ Drive/app/organize-config.yaml
```

I get this error:

```
Traceback (most recent call last):
  File "/opt/homebrew/bin/organize", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/organize/cli.py", line 213, in sim
    execute(
  File "/opt/homebrew/lib/python3.11/site-packages/organize/cli.py", line 147, in execute
    config_path, config_text = read_config(config)
                               ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/organize/cli.py", line 94, in read_config
    with fs.open_fs(dirname) as confdir:
         ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/fs/opener/registry.py", line 220, in open_fs
    _fs, _path = self.open(
                 ^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/fs/opener/registry.py", line 177, in open
    open_fs = opener.open_fs(fs_url, parse_result, writeable, create, cwd)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/fs/opener/osfs.py", line 40, in open_fs
    osfs = OSFS(path, create=create)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/fs/osfs.py", line 141, in __init__
    raise errors.CreateFailed(message)
fs.errors.CreateFailed: root path '/Users/xxx/my.domain/My Drive/app' does not exist
```

**Environment (please complete the following information):**

- OS: macOS Ventura 13.4.1 (c) (22F770820d)
- Output of `organize --version`: organize, version 2.4.0

**Your config file**

```yaml
rules:
    - locations:
        - ~/Downloads
      subfolders: true
      filters:
        - lastmodified:
            days: 7
      actions:
        - trash
```

**Comment by tfeldmann** [comment]
Hi, thanks a lot for reporting. I didn't know how to debug this but @notDavid reported #332 which I think is related.
This should be fixed in the new v3 alpha, could you retest this? Infos are in the repo's readme. Thanks a lot!

**Comment by gregoriopellegrino** [comment]
It works, thank you!
