### ISSUE TITLE
Build failure on Linux for v2.4.2

### ISSUE THREAD

**Issue by p-linnane** [tfeldmann/organize#305]
**Describe the bug**
v2.4.2 of organize fails to build on Linux, due to the new depedency on `pyobjc-framework-cocoa`. This dependency calls `/usr/bin/sw_vers` which is only on macOS.

```
 ==> python3.11 -m pip --python=/home/linuxbrew/.linuxbrew/Cellar/organize-tool/2.4.2/libexec/bin/python install --verbose --no-deps --no-binary=:all: --ignore-installed --use-feature=no-binary-enable-wheel-cache --no-compile /tmp/organize-tool--pyobjc-framework-cocoa-20230826-8399-195z4x4/pyobjc-framework-Cocoa-9.2
  WARNING: The following features are always enabled: no-binary-enable-wheel-cache.
  Using pip 23.2.1 from /home/linuxbrew/.linuxbrew/lib/python3.11/site-packages/pip (python 3.11)
  Processing /tmp/organize-tool--pyobjc-framework-cocoa-20230826-8399-195z4x4/pyobjc-framework-Cocoa-9.2
    Installing build dependencies: started
    Running command pip subprocess to install build dependencies
    Collecting setuptools
      Downloading setuptools-68.1.2.tar.gz (2.2 MB)
         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 25.8 MB/s eta 0:00:00
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'done'
      Installing backend dependencies: started
      Installing backend dependencies: finished with status 'done'
      Preparing metadata (pyproject.toml): started
      Preparing metadata (pyproject.toml): finished with status 'done'
    Collecting wheel
      Using cached wheel-0.41.2-py3-none-any.whl
    Building wheels for collected packages: setuptools
      Building wheel for setuptools (pyproject.toml): started
      Building wheel for setuptools (pyproject.toml): finished with status 'done'
      Created wheel for setuptools: filename=setuptools-68.1.2-py3-none-any.whl size=805129 sha256=a964a61ea24650bad3800283726cc4b8e42f13f3324d13cff33075be96a277c4
      Stored in directory: /tmp/organize-tool-20230826-8399-1vg4maf/organize_tool-2.4.2/.brew_home/.cache/pip/wheels/0e/b9/82/9e956644b62f2fcba3266358da9339b0a33acdf0ceb9bdc21f
    Successfully built setuptools
    Installing collected packages: wheel, setuptools
    Successfully installed setuptools-68.1.2 wheel-0.41.2
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Running command Getting requirements to build wheel
    Traceback (most recent call last):
      File "/home/linuxbrew/.linuxbrew/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
        main()
      File "/home/linuxbrew/.linuxbrew/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/linuxbrew/.linuxbrew/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
        return hook(config_settings)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/tmp/pip-build-env-05e8x2l3/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
        return self._get_build_requires(config_settings, requirements=['wheel'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/tmp/pip-build-env-05e8x2l3/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
        self.run_setup()
      File "/tmp/pip-build-env-05e8x2l3/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in run_setup
        exec(code, locals())
      File "<string>", line 20, in <module>
      File "/tmp/organize-tool--pyobjc-framework-cocoa-20230826-8399-195z4x4/pyobjc-framework-Cocoa-9.2/pyobjc_setup.py", line 541, in setup
        os_level = get_os_level()
                   ^^^^^^^^^^^^^^
      File "/tmp/organize-tool--pyobjc-framework-cocoa-20230826-8399-195z4x4/pyobjc-framework-Cocoa-9.2/pyobjc_setup.py", line 230, in get_os_level
        subprocess.check_output(["/usr/bin/sw_vers", "-productVersion"])
      File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/subprocess.py", line 466, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/subprocess.py", line 548, in run
        with Popen(*popenargs, **kwargs) as process:
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/subprocess.py", line 1026, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/subprocess.py", line 1950, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/sw_vers'
    error: subprocess-exited-with-error
    
    × Getting requirements to build wheel did not run successfully.
    │ exit code: 1
    ╰─> See above for output.
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
    full command: /home/linuxbrew/.linuxbrew/Cellar/organize-tool/2.4.2/libexec/bin/python /home/linuxbrew/.linuxbrew/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpo0ip0qnb
    cwd: /tmp/organize-tool--pyobjc-framework-cocoa-20230826-8399-195z4x4/pyobjc-framework-Cocoa-9.2
    Getting requirements to build wheel: finished with status 'error'
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Environment (please complete the following information):**

- OS: Ubuntu 22.04.3

Relates to https://github.com/Homebrew/homebrew-core/pull/140493

**Comment by tfeldmann** [comment]
Thanks for reporting. I'll look into this!

**Comment by p-linnane** [comment]
This was an issue on the Homebrew side with name normalization. It's been fixed on our side. Apologies!
