### ISSUE TITLE
Installation issue on Mac

### ISSUE THREAD

**Issue by RaviH** [tfeldmann/organize#4]
Hello,

I am having an issue installing on Mac: 10.11.6 OS X Ei Capitan

```
$ pip3 install organize-tool
Collecting organize-tool
  Using cached organize_tool-1.2-py3-none-any.whl
Collecting pyyaml (from organize-tool)
Collecting colorama (from organize-tool)
  Using cached colorama-0.3.9-py2.py3-none-any.whl
Collecting appdirs (from organize-tool)
  Using cached appdirs-1.4.3-py2.py3-none-any.whl
Collecting docopt (from organize-tool)
Collecting clint (from organize-tool)
Collecting Send2Trash (from organize-tool)
  Using cached Send2Trash-1.5.0-py3-none-any.whl
Collecting args (from clint->organize-tool)
Installing collected packages: pyyaml, colorama, appdirs, docopt, args, clint, Send2Trash, organize-tool
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.6/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python3.6/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/local/lib/python3.6/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/local/lib/python3.6/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python3.6/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/local/lib/python3.6/site-packages/pip/wheel.py", line 323, in clobber
    shutil.copyfile(srcfile, destfile)
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/lib/python3.6/site-packages/_yaml.cpython-36m-darwin.so'
```

**Comment by tfeldmann** [comment]
Hi, this looks like there is an issue with your python installation. 
Please try again with sudo:
```
sudo pip3 install organize-tool
```

This will probably fix the installation issue, but in the long run you should fix your python installation to not require root privileges when installing packages.
Did you install python via homebrew? If not, how did you do it?
