### ISSUE TITLE
[WinError 123] The filename, directory name, or volume label syntax is incorrect

### ISSUE THREAD

**Issue by tordenflesk** [tfeldmann/organize#75]
organize.exe config --debug output:

```
Config file syntax seems fine!
Traceback (most recent call last):
  File "C:\Python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python38\Scripts\organize.exe\__main__.py", line 7, in <module>
  File "C:\Python38\lib\site-packages\organize\cli.py", line 65, in main
    config_debug(config_path)
  File "C:\Python38\lib\site-packages\organize\cli.py", line 132, in config_debug
    if not fullpath(f).exists():
  File "C:\Python38\lib\site-packages\organize\utils.py", line 24, in fullpath
    return Path(os.path.expandvars(str(path))).expanduser().resolve(strict=False)
  File "C:\Python38\lib\pathlib.py", line 1172, in resolve
    s = self._flavour.resolve(self, strict=strict)
  File "C:\Python38\lib\pathlib.py", line 205, in resolve
    s = self._ext_to_normal(_getfinalpathname(s))
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '! H:\\X\\X\\X\\*upscale*.*'
```

```
rules:
  - folders:
        - H:\X\X\X
        - ! H:\X\X\X\*qtgmc*.*
        - ! H:\X\X\X\*upscale*.*
        - ! H:\X\X\X\*(AI)*.*
    filters:
        - lastmodified:
            minutes: 40
            mode: newer
        - extension:
          - mp4
          - avi
          - mpg
          - mpeg
          - wmv
          - m4v
          - flv
        - filesize: '< 1 GB'        
    actions:
      - copy:
            dest: G:\
            overwrite: true
      
    # optional settings:
    enabled: true
    subfolders: true


```

**Comment by tfeldmann** [comment]
Thank you for the bug report. I don't have a windows machine at the moment but I'll look into this when I have some time to setup a vm.

**Comment by c-condor** [comment]
Has there been any progress on this? I have the same error occur whenever I use a wildcard '*' anywhere in the folders syntax.

I was merely trying to do the following from the tutorial
```
rules:
  - folders: ~/Downloads
    subfolders: true
    actions:
      - echo: {path}
```

**Comment by tfeldmann** [comment]
Please try again with the newly released version. It should now work on windows without problems.
